// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package model

import (
	"github.com/google/uuid"
)

type Tag struct {
	ID       int32
	TextUuid uuid.UUID
	Name     string
}

type Text struct {
	ID    int32
	Uuid  uuid.UUID
	Title string
	Body  string
}
