// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: texts.sql

package model

import (
	"context"

	"github.com/google/uuid"
)

const createText = `-- name: CreateText :one
INSERT INTO texts(uuid, title, body) VALUES (gen_random_uuid(), $1, $2) RETURNING uuid
`

type CreateTextParams struct {
	Title string
	Body  string
}

func (q *Queries) CreateText(ctx context.Context, arg CreateTextParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createText, arg.Title, arg.Body)
	var uuid uuid.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const getText = `-- name: GetText :one
SELECT id, uuid, title, body FROM texts WHERE uuid = $1
`

func (q *Queries) GetText(ctx context.Context, uuid uuid.UUID) (Text, error) {
	row := q.db.QueryRowContext(ctx, getText, uuid)
	var i Text
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Title,
		&i.Body,
	)
	return i, err
}
