version: '3'
services:
  database:
    image: postgres:15.0-bullseye
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'textstack' # FIXME: read .env
      POSTGRES_USER: 'textstack'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:


